spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-server
      name: config-client
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    
server:
  port: 8882
eureka:
  client:
    eureka-server-d-n-s-name: localhost
    eureka-server-port: 8761
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh