spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/20082193/demo/
          search-paths: repo
      label: master
server:
  port: 8888
eureka:
  client:
    eureka-server-port: 8761
    eureka-server-d-n-s-name: localhost

